# Generated by Django 4.0.4 on 2022-07-04 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0056_alter_category_name'),
        ('user_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_users',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.category'),
            preserve_default=False,
        ),
    ]
