# Generated by Django 4.0.4 on 2022-07-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_register', '0002_data_users_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_users',
            name='ciudad',
            field=models.CharField(blank=True, default=None, max_length=20),
            preserve_default=False,
        ),
    ]
