# Generated by Django 4.0.4 on 2022-07-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_register', '0003_alter_data_users_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_users',
            name='ciudad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
