# Generated by Django 4.0.4 on 2022-07-04 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='user_asocied',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_asocied', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
