# Generated by Django 4.0.4 on 2022-07-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_empresas_user_asocied'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='biografia',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
