# Generated by Django 4.0.4 on 2022-07-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_tag_empresas_biografia_empresas_slug_empresas_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='empresas',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag_category', to='business.tag'),
        ),
    ]
