# Generated by Django 4.0.4 on 2022-07-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_remove_empresas_tag_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='slug',
        ),
    ]
