# Generated by Django 4.0.4 on 2022-07-05 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0008_remove_empresas_slug_remove_empresas_tag_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='category',
        ),
        migrations.AddField(
            model_name='empresas',
            name='category',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
