# Generated by Django 4.0.4 on 2022-07-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_remove_tag_slug_alter_empresas_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default_images/pagina-web.jpg', upload_to='default_images')),
            ],
        ),
    ]
