# Generated by Django 4.0.4 on 2022-06-09 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_category_empresas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='nombre',
            new_name='name',
        ),
        migrations.AddField(
            model_name='empresas',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='numero',
            field=models.IntegerField(default=15, unique=True),
            preserve_default=False,
        ),
    ]
