# Generated by Django 4.0.4 on 2022-06-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_nombre_empresas_name_empresas_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
