# Generated by Django 4.0.4 on 2022-06-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_empresas_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='username',
            new_name='usernames',
        ),
    ]
