# Generated by Django 4.0.4 on 2022-06-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_username_accounts_usernames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='usernames',
            new_name='username',
        ),
    ]
