# Generated by Django 4.0.4 on 2022-06-10 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_usernames_accounts_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='username',
            new_name='username_id',
        ),
    ]
