# Generated by Django 4.0.4 on 2022-06-10 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='username_id',
            new_name='username',
        ),
    ]
