# Generated by Django 4.0.4 on 2022-06-11 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0010_rename_username_id_accounts_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=9),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='username',
            field=models.OneToOneField(max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
