# Generated by Django 4.0.4 on 2022-06-11 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_accounts_gender_alter_accounts_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={},
        ),
    ]
