# Generated by Django 4.0.4 on 2022-06-11 00:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0012_alter_accounts_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Data_Users',
        ),
    ]
