# Generated by Django 4.0.4 on 2022-06-11 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_rename_accounts_data_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_users',
            name='password',
        ),
    ]
