# Generated by Django 4.0.4 on 2022-06-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_data_users_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_users',
            old_name='username',
            new_name='user',
        ),
    ]
