# Generated by Django 4.0.4 on 2022-06-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_data_users_email_remove_data_users_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data_Users',
        ),
    ]
