# Generated by Django 4.0.4 on 2022-06-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_data_users_image_alter_data_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_users',
            name='image',
            field=models.ImageField(default='anonymous-user.png', upload_to='profile_image'),
        ),
    ]
