# Generated by Django 4.0.4 on 2022-06-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_data_users_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_users',
            name='image',
            field=models.ImageField(default='profile_image/anonymous-user.png', upload_to='profile_image'),
        ),
    ]
