# Generated by Django 4.0.4 on 2022-06-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_data_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='image',
            field=models.ImageField(default='anonymous-business.png', upload_to='business_image'),
        ),
    ]
