# Generated by Django 4.0.4 on 2022-06-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_alter_empresas_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='image',
            field=models.ImageField(default='anonymous-business.jpg', upload_to='business_image'),
        ),
    ]
