# Generated by Django 4.0.4 on 2022-06-17 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0029_alter_empresas_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_users',
            name='user',
            field=models.OneToOneField(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='data_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
