# Generated by Django 4.0.4 on 2022-06-17 02:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_alter_data_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_users',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Usuarios', to='app1.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Empresas', to='app1.category'),
            preserve_default=False,
        ),
    ]
