# Generated by Django 4.0.4 on 2022-06-17 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_remove_empresas_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Empresas', to='app1.category'),
            preserve_default=False,
        ),
    ]
