# Generated by Django 4.0.4 on 2022-06-17 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_alter_empresas_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_users',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Usuarios', to='app1.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresas',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empresas', to='app1.category'),
        ),
    ]
