# Generated by Django 4.0.4 on 2022-06-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_data_users_category_alter_empresas_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='numero',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
