# Generated by Django 4.0.4 on 2022-06-21 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_alter_empresas_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='numero',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('-[0-9]+')]),
        ),
    ]
