# Generated by Django 4.0.4 on 2022-06-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_alter_empresas_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='image',
            field=models.ImageField(default='anonymous-business.png', upload_to='business_image'),
        ),
    ]
