# Generated by Django 4.0.4 on 2022-06-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_alter_empresas_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='numero',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
    ]
