# Generated by Django 4.0.4 on 2022-06-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_alter_empresas_numero_alter_empresas_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='CEO',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
