# Generated by Django 4.0.4 on 2022-06-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_alter_empresas_ceo_alter_empresas_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='numero',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
