# Generated by Django 4.0.4 on 2022-06-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_alter_empresas_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_users',
            name='image',
            field=models.ImageField(default='default_images/anonymous-user.png', upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='image',
            field=models.ImageField(default='default_images/anonymous-business.png', upload_to='business_image'),
        ),
    ]
