# Generated by Django 4.0.4 on 2022-06-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0051_alter_empresas_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='image',
            field=models.ImageField(default='default_images/anonymous-business.png', upload_to='business_image'),
        ),
    ]
