# Generated by Django 4.0.4 on 2022-06-30 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0052_alter_empresas_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='data_users',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='app1.category'),
        ),
        migrations.AlterField(
            model_name='data_users',
            name='user',
            field=models.OneToOneField(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='related', to=settings.AUTH_USER_MODEL),
        ),
    ]
