# Generated by Django 4.0.4 on 2022-07-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_data_users_address_data_users_ciudad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data_Users',
        ),
    ]
