# Generated by Django 4.0.4 on 2022-07-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0056_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
